version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    links:
      - mysql:db
  mysql:
    image: "mysql:5.7.10"
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    volumes:
      - "./data:/var/lib/mysql"
